SWM-KAWAI-MANS/party-run-application

app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt, app/src/main/java/online/partyrun/partyrunapplication/data/mockTest/TestDataSource.kt, app/src/main/java/online/partyrun/partyrunapplication/data/mockTest/TestRepositoryImpl.kt, app/src/main/java/online/partyrun/partyrunapplication/di/ConfigModule.kt, app/src/main/java/online/partyrun/partyrunapplication/di/RemoteModule.kt, app/src/main/java/online/partyrun/partyrunapplication/di/RepositoryModule.kt, app/src/main/java/online/partyrun/partyrunapplication/domain/mockTest/TestRepository.kt, app/src/main/java/online/partyrun/partyrunapplication/domain/mockTest/TestUseCase.kt, app/src/main/java/online/partyrun/partyrunapplication/network/ApiResponse.kt, app/src/main/java/online/partyrun/partyrunapplication/network/ApiResult.kt, app/src/main/java/online/partyrun/partyrunapplication/network/ErrorResponse.kt, app/src/main/java/online/partyrun/partyrunapplication/network/api/AuthApiService.kt, app/src/main/java/online/partyrun/partyrunapplication/network/api/mockTest/TestApiService.kt, app/src/main/java/online/partyrun/partyrunapplication/network/apiCallAdapter/ApiResultCall.kt, app/src/main/java/online/partyrun/partyrunapplication/network/apiCallAdapter/ApiResultCallAdapter.kt, app/src/main/java/online/partyrun/partyrunapplication/network/apiCallAdapter/ApiResultCallAdapterFactory.kt, app/src/main/java/online/partyrun/partyrunapplication/network/apiCallAdapter/handleApi.kt, app/src/main/java/online/partyrun/partyrunapplication/network/models/mockTest/QuestionItem.kt, app/src/main/java/online/partyrun/partyrunapplication/presentation/components/GoogleButton.kt, app/src/main/java/online/partyrun/partyrunapplication/presentation/screens/mockTest/TestScreen.kt, app/src/main/java/online/partyrun/partyrunapplication/presentation/screens/mockTest/TestViewModel.kt, app/src/main/java/online/partyrun/partyrunapplication/presentation/screens/signin/SignInScreen.kt, app/src/main/java/online/partyrun/partyrunapplication/presentation/screens/signin/SignInViewModel.kt, app/src/main/java/online/partyrun/partyrunapplication/presentation/screens/splash/SplashScreen.kt, app/src/main/java/online/partyrun/partyrunapplication/presentation/screens/splash/SplashViewModel.kt, app/src/main/java/online/partyrun/partyrunapplication/util/ApiFlow.kt, app/src/main/java/online/partyrun/partyrunapplication/util/Constants.kt, app/src/main/res/drawable/google_logo.xml
Trivia URL(itmmckernan/triviaJSON)을 통한 SafeApiCall Test -> mockTest Directory
=> feat : SafeApiCall Layer Design #PAR-51

.gitignore, app/build.gradle.kts, buildSrc/build.gradle.kts, buildSrc/src/main/java/Configurations.kt
* 상용구 코드를 최소화하고 configuration 버전 관리를 위한 buildSrc 생성
=> refactor : buildSrc for configuration version management

app/src/main/java/online/partyrun/partyrunapplication/AuthActivity.kt, app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt, app/src/main/java/online/partyrun/partyrunapplication/di/DefaultTokenExpirationNotifier.kt, app/src/main/java/online/partyrun/partyrunapplication/di/TokenExpirationModule.kt, core/common/src/main/java/online/partyrun/partyrunapplication/core/common/ExtraConstants.kt, feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt, feature/battle/src/main/res/values/strings.xml, feature/challenge/src/main/res/values/strings.xml, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchDecisionDialog.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchResultDialog.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt, feature/match/src/main/res/values/strings.xml, feature/my_page/src/main/res/values/strings.xml, feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInScreen.kt, feature/sign_in/src/main/res/values/strings.xml, feature/single/src/main/res/values/strings.xml, feature/splash/src/main/res/values/strings.xml
프로젝트내 모든 커스텀 String 문자열 리소스를 res/value/string.xml에서 관리한다.
string resource를 사용하여 선택적 텍스트 스타일 및 서식 지정을 통한 애플리케이션에 대한 텍스트 문자열 제공
다음과 같은 이점을 얻을 수 있다.
1. 지원하려는 각 언어에 대한 String 리소스 파일을 통해 다양한 언어를 지원
2. stringResource에서 한 번만 정의하고 사용해야 할 때마다 참조 -> 유지보수성 향상, 오류 가능성 감소
- 동일한 문자열을 여러 번 사용하는 경우 중복 방지
- 나중에 해당 문자열을 변경해야 하는 경우 문자열 리소스 파일만 변경하면 됨.
=> #PAR-123 : Module별 String Resource 참조 및 Constants 작업

feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
waitForUserDecision()에서 사용자가 선택한 true/ false에 대한 리턴값이 제대로 전달되지 않는 이슈
사용자의 수락/ 거절 상태에 따른 Boolean값 변화를 Flow로 변경
Boolean값의 return을 withTimeoutOrNull안에서 하는게 아니라 바깥에서 처리하도록 변경
=> #PAR-135 : 매칭 과정 중 수락/거절 값이 제대로 전달되지 않는 문제

feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt
=> refactor : Disconnect 단어 포맷 변경

core/data/src/test/java/online/partyrun/partyrunapplication/core/data/repository/SignInRepositoryImplTest.kt
1. 더 간결하고 결과 비교에 최적화된 표현방식으로 flow에 collect()이 아닌 last()로 테스트코드 변경
2. 보다 명확한 의미를 표현하고자 expectedResponse -> mockResponse로 변경
#29
=> refactor : flow.last()를 활용한 테스트 코드 단순화

core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running/RecordData.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/RealtimeBattleClient.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
1. 명확하지 않은 표현인 Datas 대신 gpsDatas에 대한 네이밍을 수정 → Record
2. type → “start”가 아닌 “BATTLE_START_TIME”으로 수정
=> #PAR-162 : 백엔드와의 네이밍 통일

core/network/src/main/java/online/partyrun/partyrunapplication/core/network/RealtimeBattleClient.kt
BASE_URL의 "http://" 부분을 제거하기 위해 작성한 코드 중 블록 처리와 CharSequence 부분 수정
=> refactor : removePrefix()의 CharSequence 수정

app/src/main/java/online/partyrun/partyrunapplication/AuthActivity.kt, app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt, app/src/main/java/online/partyrun/partyrunapplication/ui/PartyRunAuth.kt, app/src/main/res/values/strings.xml
초기에 프로젝트를 진행하면서 신경쓰지 못해 불필요하거나 헷갈리는 부분이 많은 App모듈 단의 Auth, Main Activity 부분 리팩토링 수행
1. AuthActivity의 NavGraph 부분을 별도 Composable화 분리
2. 중복되는 Intent 코드 -> 메소드로 추출
=> #PAR-160 : app모듈 리팩토링 진행

.github/workflows/android.yml
=> gradle-build-action를 사용하여 설정 단순화 및 캐시 최적화

feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInScreen.kt
=> refactor : SignInScreen Box Composable 제거

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleUiState.kt
멤버 서비스가 아직 구축되지 않았음에 따라 1차적인 대결 종료 이후 프로세스를 작성.
1. 웹소켓 서버로부터 종료 이벤트가 오면, 내 ID와 비교해 맞는지 틀린지 확인
2. 맞다면, 반투명의 FinishScreen을 띄워줌.
=> #PAR-246 :  목표 거리에 도달해 대결을 종료하기 위한 1차 프로세스 구축

core/network/src/main/java/online/partyrun/partyrunapplication/core/network/RealtimeBattleClient.kt
1. 대결 모드를 위한 WebSocket 연결 API 명세가 바뀜에 따라 변경사항에 맞게 URL 수정
2. RealtimeBattleClient 메소드 관련 기능 설명 주석 추가
=> refactor : WebSocket 연결을 위한 Url 변경 및 BattleClient 주석 추가

core/network/src/main/java/online/partyrun/partyrunapplication/core/network/di/ApiServiceModule.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/BattleResultApiService.kt
=> fix : Battle 결과를 얻어오는 과정에서의 네트워크 관련 이슈 해결을 위한 디테일 수정

feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt, feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainUiState.kt, feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainViewModel.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultViewModel.kt
=> refactor : Battle Main, Result에 sealed class UiState 적용

core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/running/GetUserIdUseCase.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/running/BattleRunningScreen.kt
대결이 종료되어 handleBattleFinished()가 호출되면
멤버서비스로부터 받아온 내 userId와 서버로부터 받은 runnerId가 같은지 판단하고,
같다면 finishScreen을 띄운 뒤 3초 대기 후 결과 페이지로 이동
=> #PAR-249 : ID를 비교해 내 아이디가 맞다면 결과 페이지로 이동하는 프로세스 구현

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleScreenState.kt
=> refactor : FinishScreen 전환을 BattleContentScreen에서 수행하도록 변경

core/model/src/main/java/online/partyrun/partyrunapplication/core/model/util/LocalDateTimeAdapter.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleResultResponse.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleRunnerStatusResponse.kt
=> #PAR-275 : 문자열 형태로 표현된 날짜와 시간 정보를 LocalDateTime 객체로 변환하기 위한 포맷터 처리

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/running/BattleRunningScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultViewModel.kt
=> chore : 불필요한 코드 제거 및 라인 정리

core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleResult.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleRunnerStatus.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultUiState.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultViewModel.kt
기존 mock Data를 통해 보여주던 결과 스크린에서의 러너들의 정보를 서버로부터 받아온 데이터로 적절하게 바인딩하여
UI 상에서 보여줄 수 있도록 한다.
=> #PAR-281 : 결과 화면에서 러너들의 정보를 보여준다.

feature/running_result/build.gradle.kts, gradle/libs.versions.toml
대결 결과 혹은 싱글 결과에서 러너의 경로 추적 PolyLine을 보여주기 위한
Google Map, Location Dependency 추가
=> chore : GoogleMap, Location dependency 추가

app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt, app/src/main/res/values/strings.xml, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/main/BottomBarItem.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/main/BottomNavBarItems.kt
=> #PAR-286 : NavigationBar 기능 출시 여부 판단을 위한 "준비중" 뱃지 작업

app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt, app/src/main/java/online/partyrun/partyrunapplication/ui/PartyRunMain.kt, app/src/main/res/xml/data_extraction_rules.xml, build-logic/convention/src/main/kotlin/AndroidLibraryConventionPlugin.kt, core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/ApiFlow.kt, core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/Button.kt, core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/IconButton.kt, core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/Navigation.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/settings/SettingsNavigation.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/single/SingleNavigation.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/SignInDataSourceImpl.kt, core/ui/src/main/java/online/partyrun/partyrunapplication/core/ui/ProfileSection.kt, feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchUiState.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchCancelDialog.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchDecisionDialog.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchResultDialog.kt, feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultUiState.kt, feature/settings/src/main/java/online/partyrun/partyrunapplication/feature/settings/SettingsScreen.kt, feature/settings/src/main/java/online/partyrun/partyrunapplication/feature/settings/UnsubscribeScreen.kt, feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInScreen.kt, feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashViewModel.kt
=> refactor : sona issue 반영 1차

app/src/main/AndroidManifest.xml
Implement permissions on this exported component.
Exported component access should be restricted with appropriate permissions 에 따른 수정
=> fix : MainActivity exported false로 변경

core/network/src/main/java/online/partyrun/partyrunapplication/core/network/RealtimeBattleClient.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
사용자가 대결 중 대결을 종료하려고 할 때,
단순히 메인으로 돌아가는 것 뿐만 아니라, 연결된 구독 해지와 웹소켓 연결을 종료해야 한다.
따라서, 먼저 구독 및 웹소켓 연결을 종료하고 메인으로 돌아간다.
=> #PAR-300 : 대결 중 BackPressed 시 구독 및 웹소켓 종료 작업 수행

core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/GoogleAuthRepository.kt, core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/GoogleAuthRepositoryImpl.kt, core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/auth/GoogleSignInUseCase.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/GoogleAuthClient.kt, core/testing/src/main/java/online/partyrun/partyrunapplication/core/testing/repository/TestGoogleAuthRepository.kt, feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInViewModel.kt
=> #PAR-303 : 구글 원탭 클라이언트에서 저장된 사용자 인증 정보를 찾을 수 없을 때 스낵 메세지 알림

app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt, core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/TextField.kt, core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/icon/PartyRunIcons.kt, core/designsystem/src/main/res/drawable/ic_round_edit_24.xml, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/main/MainNavRoutes.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/my_page/MyPageNavigation.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileErrorState.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileUiState.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileViewModel.kt, feature/my_page/src/main/res/values/strings.xml
프로필 정보 수정을 위한 Profile Presentation 추가
닉네임 수정에 관한 로직 구성 완료
API가 만들어지는대로 연동 예정
추후 프로필 이미지 수정까지 적용 예정
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/d3347946-bb07-43bd-8ea0-3efa26d520da
=> #PAR-302 : 닉네임 수정을 위한 Profile Presentation 추가

feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
BattleMainBdoy Composable를 좀 더 목적에 맞게 분리하는 리팩토링 진행
=> refactor : BattleMainBody Composable 리팩토링

core/common/src/main/java/online/partyrun/partyrunapplication/core/common/result/Result.kt, core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/BattleRepositoryImpl.kt, core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepositoryImpl.kt, core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MemberRepositoryImpl.kt, core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/ResultRepositoryImpl.kt, core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/SignInRepositoryImpl.kt, core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/running_result/GetBattleResultUseCase.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleResult.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleRunnerRecord.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleRunnerStatus.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/ui/BattleResultUiModel.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/ui/BattleRunnerRecordUiModel.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/ui/BattleRunnerStatusUiModel.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleRunnerRecordResponse.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleRunnerStatusResponse.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/util/FormatLocalDateTime.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultUiState.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultViewModel.kt, feature/running_result/src/main/res/values/strings.xml
러너별로 달린 시간, 페이스, 평균 고도를 계산하여 보여줄 수 있도록 한다.
페이스는 1Km를 달리는데 몇 분이 걸리는가를 나타낸다.
애뮬레이이터 GPS를 다룬 결과이므로 고도는 0.0로 고정인 상태
=> #PAR-315 : 결과 화면에서 페이스, 시간, 평균 고도를 보여준다.

core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleRunnerRecord.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleRunnerStatus.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/ui/BattleRunnerRecordUiModel.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/ui/BattleRunnerStatusUiModel.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleRunnerRecordResponse.kt, core/ui/src/main/java/online/partyrun/partyrunapplication/core/ui/LineChart.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/ChartScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt, feature/running_result/src/main/res/values/strings.xml
결과 스크린에서 분석 차트를 제공한다.
분석 차트는
달린 시간 비율에 따른 거리, 페이스, 고도를 보여준다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/034e7bc5-f708-4300-868d-082e99605d22
=> #PAR-316 : 결과 스크린에 분석 차트 제공 

app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
현재 결과 스크린에서 뒤로 가기를 할 경우, Running스크린으로 다시 돌아간다.
결과 스크린에서 뒤로 가기를 할 경우, 메인 스크린으로 전환 될 수 있도록 변경한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/2d3f4e38-f136-4634-94ba-01c335a8e8a2
=> #PAR-320 : 결과에서 뒤로 가기를 할 경우, 메인으로 가도록 수정

feature/battle/build.gradle.kts, feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt, feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/CheckMultiplePermissions.kt, feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/PermissionDialog.kt, feature/battle/src/main/res/values/strings.xml, gradle/libs.versions.toml
사용자의 디바이스에서 파티런 퍼미션이 허용되어 있는지 확인한다.
필수 퍼미션은 다음과 같다.
Manifest.permission.POST_NOTIFICATIONS
Manifest.permission.ACCESS_FINE_LOCATION
최초 1회 퍼미션 확인을 받고, 만약 허용을 하지 않았다면 러닝이 불가능해야 한다.
따라서, 매칭 잡기를 눌렀을 때 퍼미션을 확인하고, 정해진 퍼미션에 대해 허용이 되어 있지 않다면
퍼미션 설정에 대한 안내를 진행한다
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/b07b495a-e9a8-469b-a8b7-2afdba6ef201
=> #PAR-240 : 러닝을 위한 필수 퍼미션 권한 획득 유도

app/build.gradle.kts, app/src/main/java/online/partyrun/partyrunapplication/AuthActivity.kt, app/src/main/res/values/strings.xml, gradle/libs.versions.toml
사용자 기기에서 앱을 최신 상태로 유지시킬 수 있도록 업데이트 기능을 추가한다.
액티브 사용자에게 앱 업데이트 메시지를 표시하는 새로운 방식을 도입한 Play Core 라이브러리인 In-App-Update API를 활용한다.
업데이트 방식은 Immediate updates와 Flexible updates가 있는데,
현재는 Flexible updates 방식으로 설정하여 구현.
Flexible updates는 다음과 같은 이점이 있다.
1. 상태 모니터링 기능
2. 백그라운드 다운로드 및 설치
3. 사용자가 업데이트를 다운로드하는 동안 앱 사용 가능
=> #PAR-330 : 앱을 최신 상태로 유지시킬 수 있도록 In App Update API 연동

feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleScreen.kt
PartyRunMatchButton의 onClick 로직을 리팩터링하여 readability과 maintainability 개선
다중 조건 체크를 별도의 함수로 추출하여 shouldExecuteMatchingAction() 수행
=> refactor : PartyRunMatchButton onClick 로직에서의 더 나은 가독성을 위한 리팩토링 수행

app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/running/RunningNavigation.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
싱글 모드 결과 스크린 구성 전, 만들어지기 전 임시로 MainNavRoutes.Single로 전환
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/31d9ccb1-c4b1-43ba-b7eb-bbc4ec6f7c7d
=> feat : SingleRunning 중 목표거리 도달 후 Single 메인으로 전환

app/src/main/java/online/partyrun/partyrunapplication/navigation/AuthNavHost.kt, app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt, core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/TopApp.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/auth/AuthNavigation.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/my_page/MyPageNavigation.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/running/RunningNavigation.kt, core/ui/src/main/java/online/partyrun/partyrunapplication/core/ui/AgreementTopAppBar.kt, core/ui/src/main/java/online/partyrun/partyrunapplication/core/ui/SettingsTopAppBar.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/component/RunningTopAppBar.kt, feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/agreement/AgreementScreen.kt, feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashScreen.kt
기존 navigateTo~~~ 외에 navigationTo~~~로 명명되어 있던 네비게이션 파라미터명들을
navigateTo~~~로 통일하는 리팩토링 작업 수행
=> refactor : navigationTo__ -> navigateTo__ 파라미터명 통일을 위한 수정

feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleViewModel.kt
싱글모드에서 목표거리를 선택하는 경우,
0.25 Km 이하로는 설정 못하도록 조건문을 넣었는데 부등호에 =가 들어가 0.00 km까지 내려가는 경우가 발생
=를 빼줌으로써 최소 0.25km로 고정
=> refactor : TargetDistance 부등호 수정

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/SingleRunningService.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt, feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleViewModel.kt
1. SingleViewModel 매직넘버들을 상수로 정의
2. SingleRunningService 코드 리팩토링 -> 명확한 함수 분리
3. SingleContentScreen 중복 함수 최소화
=> refactor : Single Feature 리팩토링 수행 

core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/ApiFlow.kt
1. 불필요한 code별 errorMessage 분기 처리 제거 
2. Timeout 발생 시 에러 메세지에 Timeout 시간 명시
=> refactor : ApiFlow 전반적인 리팩토링 수행

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/BattleRunningScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/SingleRunningScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/util/RunningConstants.kt
feature/running Module에서 사용되는 매직넘버를 RunningConstants로 대체
=> refactor : feature/running Module 매직넘버 상수로 대체

core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/battle/BattleRunnerStatus.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/single/SingleRunnerStatus.kt, core/model/src/main/java/online/partyrun/partyrunapplication/core/model/util/RunningRecordCalculation.kt
의미를 명확히 하기 위한 메소드명 수정
전체 경과 시간과 해당 시간에서의 총 거리를 기반으로 분/킬로미터 페이스를 구하는 메소드이므로
calculatePacePerMinute -> calculateCumulativePacePerMinute로 변경
=> refactor : calculatePacePerMinute -> calculateCumulativePacePerMinute

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/BattleRunningService.kt
서버로 GPS data를 3개씩 쌓아 전송하는데, 이떄의 SEND 임계값을 상수로 대체
=> refactor : BattleRunningService 매직넘버 상수로 대체

core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleMemberResponse.kt, core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/UserResponse.kt
멤버 Response로 오는 Proflle URL과 S3_URL 문자열을 concat 시
Profile Image URL 앞에 "/" 처리 추가
=> feat : Profile Image URL 앞에 "/" 처리

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/component/SingleRunnerMarker.kt
RunningScreen에서 러너 이미지 사이즈에 맞게 fillMaxSize 적용
=> feat : RunnerMarker fillMaxSize 적용

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
최소 거리 도달 후 사용자가 스스로 종료하는 경우에도 GPS 데이터 전달해 결과 조회가 이루어질 수 있도록 한다.
=> feat : 최소 거리 도달 후 종료하는 경우 GPS 데이터 전달

core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/main/BottomNavBarItems.kt
같이 하기 기능이 구현됨에 따라 isLaunched를 true로 변경한다.
=> refactor : Party isLaunched = true로 변경

feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/PartyViewModel.kt, feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/join/PartyJoinDialog.kt
PartyJoinDialog에서 JoinButton 버튼을 클릭할 때 partyCodeInput의 유효성을 검사한다.
1. 6자리인지 판단 
2. 문자열 내의 모든 문자가 숫자인지 판단
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/0c9cd123-ef11-467d-9cb0-b2b55b81db6b
=> #PAR-366 : 방 번호 입력에 대한 유효성 검사

core/model/src/main/java/online/partyrun/partyrunapplication/core/model/party/PartyEvent.kt, feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/room/PartyRoomViewModel.kt
서버 측과의 협의 하에 기존 participants를 ParticipantIds로 네이밍 변경
=> refactor : participants -> participantIds로 변경

feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileViewModel.kt
updateUserData() 리팩토링 수행
* Early Exit:
passAllConditions()의 결과가 false일 때, 함수를 조기 종료하도록 변경
=> refactor : updateUserData() return@launch 활용

feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt
마이페이지 업데이트 진행 중에는
1.  다른 터치가 불가능하도록 블락 처리
2. 반투명 처리
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/27c6afd9-b385-4dce-9b67-4d2db037bf65
=> feat : 프로필 변경 Progress 시 터치 블락 기능 추가

feature/running/src/main/res/values/strings.xml
Battle : 
* 변경 전 : 잠시 뒤 배틀이 시작 됩니다 ! 
* 변경 후 :잠시 뒤 대결이 시작됩니다!
Single : 
* 변경 전 : 5초 뒤 배틀이 시작 됩니다 !
* 변경 후 : 잠시 뒤 대결이 시작됩니다!
=> refactor : ReadyScreen ready comment 수정

feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt
마이페이지 처리 방식 Progress Dialog로 리팩토링
=> refactor : 마이페이지 처리 방식 Progress Dialog로 리팩토링

feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/room/PartyRoomScreen.kt, feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/room/PartyRoomViewModel.kt
Room번호 Clipboard 안내 메세지를 Toast에서 Snack으로 변경
=> refactor : Room번호 Clipboard -> Toast에서 Snack으로 변경

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt
MINIMUM_FINISH_DISTANCE 50 -> 30으로 변경
=> refactor : MINIMUM_FINISH_DISTANCE 50 -> 30으로 변경

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/SingleRunningService.kt
FusedLocationProviderClient 클래스의 onLocationResult 메서드는 위치 업데이트가 있을 때 호출되며, 이 메서드 내의 lastLocation 객체는 최근의 위치 데이터를 제공한다. 이 객체 내에 speedAccuracyMetersPerSecond와 accuracy라는 두 속성있는데, 각각 속도의 정확도와 위치의 정확도를 나타낸다.
이 값들의 유의미한 임계값을 여러 상황에서 찾아보고 적용한다.
**자세한 내용은 노션 참고.**
* 본 PR에서 적용한 speedAccuracyMetersPerSecond, accuracy 외에 다른 GPS 필터링 수단까지 다 적용한 종합적인 결과.
=> #PAR-374 : Single isLocationAccuracyAcceptable GPS 데이터 필터링 추가 로직 적용

feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/SingleRunningService.kt
0.07과 17이라는 값들을 상수로 변환 -> 가독성과 유지보수성을 향상
private const val MAXIMUM_SPEED_ACCURACY = 0.07 // meters/second
private const val MAXIMUM_LOCATION_ACCURACY = 17 // meters
=> refactor : Location Accuracy 임계값 매직넘버 상수화

core/common/src/main/AndroidManifest.xml, core/common/src/main/java/online/partyrun/partyrunapplication/core/common/util/TTSManager.kt, core/common/src/main/java/online/partyrun/partyrunapplication/core/common/util/VibrateDeviceManager.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/SingleRunningScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/SingleUserPausedScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/component/ControlPanelColumn.kt, feature/running/src/main/res/values/strings.xml
Running 시작, 중지, 재개에 디바이스 Vibrate와 TTS를 적용한다.
1. 러닝 시작 시, "러닝을 시작합니다" TTS와 함께 short vibrate 적용
2. 러닝 중지 시, "러닝을 중지합니다"  외 동일
3. 러닝 재개 시, "러닝을 재개합니다." 외 동일
=> #PAR-378 : Running 시 디바이스 VIBRATE & TTS 메시지 적용 

app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/my_page/MyPageNavigation.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/settings/SettingsNavigation.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt, feature/my_page/src/main/res/values/strings.xml, feature/settings/src/main/java/online/partyrun/partyrunapplication/feature/settings/SettingsScreen.kt, feature/settings/src/main/java/online/partyrun/partyrunapplication/feature/settings/SettingsViewModel.kt, feature/settings/src/main/res/values/strings.xml
로그아웃 로직을 feature/settings에서 처리하도록 기능 전환
=> refactor : 로그아웃 로직을 feature/settings에서 처리하도록 변경

app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/my_page/MyPageNavigation.kt, core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/running_result/RunningResultNavigation.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/battle/BattleResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/single/SingleResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/ui/FixedBottomNavigationSheet.kt
1. MyPage에서 러닝 결과를 조회한 경우, '돌아가기'를 눌렀을 때 다시 MyPage로 NavBack
2. 러닝 종료 상황에서 러닝 결과를 조회한 경우, '돌아가기'를 눌렀을 때 TopLevel로 Navigation
단순히 2가지 상황으로만 navigation이 이루어지기에 NavBool로 arg 처리 진행
=> feat : 러닝 결과 스크린에서 '돌아가기'를 눌렀을 때 navigation 분기처리

feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt, feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt, feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/SingleUserPausedScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/battle/BattleResultScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/component/ChartScreen.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/component/FixedBottomNavigationSheet.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/component/MapWidget.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/component/ResultBody.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/component/SummaryInfo.kt, feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/single/SingleResultScreen.kt
ProfileBackNavigationHandler 제거 후 getMyPageUserData()를 LaunchedEffect로 처리
=> refactor : 마이페이지 UserData GET 처리 방식 변경

app/build.gradle.kts, core/common/build.gradle.kts, core/data/build.gradle.kts, core/ui/src/main/java/online/partyrun/partyrunapplication/core/ui/SnackbarBox.kt, core/ui/src/main/res/values/strings.xml
1. core:common import * 제거 및 명시적 선언
2. refactor : core:data 컨벤션에 정의된 중복 Hilt 의존성 제거
3. refactor : SnackbarBox strings.xml로 문자열 처리
4. refactor : App Module import * 수정 및 컨벤션 적용 후 중복 선언 제거
=> refactor : 프로젝트 내 불필요한 코드 및 일부 사항 리팩토링

buildSrc/src/main/java/Configurations.kt
refactor : 컨벤션 플러그인에 정의된 불필요한 kotlinCompilerExtensionVersion Configuration 정의 제거
=> refactor : 컨벤션 플러그인에 정의된 불필요한 kotlinCompilerExtensionVersion Configuration 제거
