- app/src/main/java/online/partyrun/partyrunapplication/AuthActivity.kt
- app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt
- app/src/main/java/online/partyrun/partyrunapplication/di/DefaultTokenExpirationNotifier.kt
- app/src/main/java/online/partyrun/partyrunapplication/di/TokenExpirationModule.kt
- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/TokenExpirationNotifier.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/AuthAuthenticator.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/AuthInterceptor.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/di/NetworkModule.kt
자주 서비스를 이용하는 유저에게는 지속적으로 로그인 상태를 유지시켜줘야 한다.
오랜만에 로그인한 유저는 Token이 만료됐으므로 재로그인하는 과정을 거쳐야 한다.
Access Token 만료 → 새로운 Access Token을 발급 받을 경우, Refresh Token이 유효하다면
Access Token과 Refresh Token을 둘 다 Update
만약, Refresh Token이 유효하지 않다면,
구글 로그아웃을 진행한 후
tokenExpireationNofier를 통해 재로그인을 하도록 로그인 창으로 전환 진행
백엔드에서 Refresh Token 재발급. 현재 14일
테스트 케이스: 로그인 후 14일 두었을 때 로그인 화면으로 가지 않아야 함.
> #PAR-84 : Authentication 프로세스 변경

- feature/battle/build.gradle.kts
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt
클라이언트에서 매칭잡기를 시작해 다이얼로그를 띄울 때, ExoPlayer와 PlayerView(buildExoPlayer, buildPlayerView)를 빌드하는 과정에서 생기는 검은색 화면을 최소화해야 한다.
미리 빌드해놓고 필요할 때 띄워주는 방식으로 구현하는 로직은 구현해놨지만, 두 build 메소드를 호출하는 위치가 잘못되어 항상 처음부터 ExoPlayer를 build를 진행하는 문제 발생.
buildExoPlayer는 Battle에 관한 메인 Screen Composable이 만들어질 때 호출이 되고,
다이얼로그를 띄울 때 buildPlayerView를 함으로써 별도의 ExoPlayer의 빌드 과정이 없이도 Player를 보여주도록 한다.
> #PAR-126 : PreLoad를 위한 Builder 위치 변경

- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/MatchSourceManager.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/match/WaitingEventResult.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/MatchSourceManagerImpl.kt
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchUiState.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt
매칭 과정 프로세스는 다음과 같다.
REST -> SSE -> REST -> SSE -> REST
이 중 SSE 프로세스가 끝나고 난 뒤 REST 메소드를 수행해야 하는데, SSE 프로세스가 진행 중임에도 다음 REST로 넘어가는 이슈 발생
CompletableDeferred를 통해 SSE 프로세스 동작 과정 추적
> #PAR-134 : SSE 프로세스가 끝난 뒤 다음 REST를 수행하도록 보장

- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/battle/BattleNavigation.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/challenge/ChallengeNavigation.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/main/MainNavGraph.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/my_page/MyPageNavigation.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/single/SingleNavigation.kt
기존 Navigation 모듈에서 MainNavGraph 하나로 모든 feature별 네비게이션을 담당하게 했었음.
코드 수가 증가할 것을 고려해 feature모듈별 Navivation 분리해서 관리하기로 변경 
NavGraphBuilder 사용하는 이유 :
그래프의 크기가 커질수록 관리가 필요함 -> 그래프를 여러 메서드로 분할할 수 있도록 Navigation Builder구축
각 feature 별로 디렉토리를 생성해 Navigation Builder 생성
> #PAR-154 : Navigation 모듈에서 feature별로 NavGraphBuilder 관리

- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/exception/MatchingProcessException.kt
매칭 과정은 하나의 코루틴 메소드안에서 여러 세부적인 메소드들이 순차적으로 수행되어야 한다.
그러나 매칭 과정 중 예외가 발생하거나 혹은 사용자가 중간에 매칭을 취소하는 등의 상황이 발생할 경우,
이 매칭 프로세스를 총괄하는 코루틴 메소드 자체에 대한 판단을 설정할 수 있어야 한다.
메소드를 종료시킬 것이라면 예외를 던져 처리하는 것이 가장 쉽게 처리할 수 있을 것이라 판단.
MatchingProcessException 커스텀 예외 클래스 생성
예외를 던지면 코루틴의 실행이 즉시 중단되고, 해당 예외를 catch하는 부분으로 제어가 이동하기에 이를 통해 코루틴 메소드를 종료하거나 예외 처리를 수행하도록 변경
>  #PAR-157 : 매칭 과정을 총괄하는 코루틴 메소드를 종료시키기 위한 커스텀 예외 클래스 생성

- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
전반적으로 camelCase를 따르므로 의도와는 다르게 대문자로 작성된 해당 변수명의 첫글자를 소문자로 변경합니다.
#27
> refactor : MatchSourceManager에 camelCase 스타일 적용

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleUiState.kt
배틀을 위한 웹소켓 커넥션 과정부터 카운트다운 그리고 Running 상태를 보여줄 스크린의 전환이 유동적으로 이루어져야 한다.
또한, onEach{ ..} 블록을 활용해 복잡한 코드를 제거하고 간결하게 처리할 수 있도록 수정한다.
1. BattleScreenState의 Flow를 별도로 관리하지 않고 BattleUiState 안에서 처리함으로써 보다 유동적인 UI 변경의 이점을 취함
2. 기존에 추가적인 resultResult.collect { ... } 을 통해 Result 이벤트값들을 처리했다면, onEach{..}을 최대한 활용해 더 간결하게 처리하게끔 수정
> #PAR-163 : 배틀 프로세스 단계에 따른 유동적인 UI 변경과 onEach 블록 활용

- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/MatchSourceManager.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/MatchSourceManagerImpl.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
okhttp 내부 메소드명에 따라 메소드명을 일치시키기 위한 작업 수행
okhttp-sse -> EventSources
1. 리스너를 생성하는 과정은 get 대신 create로 통일
2. connect으로 event를 연결하므로 취소하는 과정은 disconnect로 통일
> #PAR-161 : MatchListener 관련 메소드명 페어 통일

- app/src/main/java/online/partyrun/partyrunapplication/di/RefreshTokenExpirationNotifier.kt
- app/src/main/java/online/partyrun/partyrunapplication/di/TokenExpirationModule.kt
- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/RefreshTokenExpirationNotifier.kt
- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/TokenExpirationNotifier.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/AuthAuthenticator.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/di/NetworkModule.kt
1. Refresh Token이 완료 되었을 때 Intent를 위한 Notifier 이므로 리프레시 토큰이 만료될 때 애플리케이션의 시작 화면으로 돌아가는 작업을 수행한다는 것을 명확하게 나타내기 위해 Notifier 클래스 네이밍 변경
2. "on"으로 시작하는 메소드 이름은 일반적으로 이벤트 리스너(event listener)에서 주로 볼 수 있는데, 특정 이벤트가 발생했을 때 이를 처리하는 메소드임을 나타내는 네이밍 컨벤션이다. 예를 들어, 사용자가 버튼을 클릭했을 때 발생하는 이벤트를 처리하는 메소드는 onClick(), 특정 값이 변경되었을 때 발생하는 이벤트를 처리하는 메소드는 onChange()와 같이 이름을 지을 수 있다. 그러나,  Notifier 클래스는 특정 상황에서 다른 객체나 시스템에 정보를 전달하는 역할을 하는 경우가 많다. 따라서 메소드 이름에는 "notify", "alert", "update", "send" 등의 동사가 자주 사용되며 이는 Notifier 클래스가 다른 객체나 시스템에 정보를 전달하는 역할을 명확하게 보여준다.
위와 같은 이유로 Notifier클래스의 메소드명을 변경한다.
1. DefaultTokenExpirationNotifier.kt -> RefreshTokenExpirationNotifier.kt 클래스명 변경
2. onTokenExpired() -> notifyRefreshTokenExpired() 메소드명 변경
> refactor : TokenExpirationNotifier 명명규칙 변경

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/datasource/MatchDataSource.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/datasource/MatchDataSourceImpl.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/di/DataSourceModule.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepositoryImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/SendAcceptMatchUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/SendDeclineMatchUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/SendWaitingMatchUseCase.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/di/ApiServiceModule.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/MatchDecisionApiService.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/WaitingMatchApiService.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
매칭과 관련된 부분들의 네이밍 정보를 보다 간결하게 변경함으로써 그 역할과 동작을 명확하게 나타내고자 리팩토링 작업 수행
예를 들어,
registerToBattleMatchingQueue, acceptBattleMatchingQueue, declineBattleMatchingQueue 등은 서버에 '등록', '수락', '거절' 액션을 보내는 역할을 한다. 그러나, Queue는 프론트에서 실제 작업과 관련이 없으므로 이를 제거하고, 더욱 간결하고 명확한 명칭으로 변경한다.
> refactor : Match-related classes 전반적인 네이밍 리팩토링 수행

- app/build.gradle.kts
- app/src/main/java/online/partyrun/partyrunapplication/ui/PartyRunMain.kt
배틀이 시작되는 순간부터는 메인과는 달리 BottomNavigationBar 없이 배틀 화면이 스크린의 전체를 차지해야 한다.
Route에 따라 BottomNavigationBar Composable의 렌더링 여부를 결정한다.
> #PAR-219 : 배틀 시작부터 BottomNavigationBar 제외

- app/src/main/java/online/partyrun/partyrunapplication/AuthActivity.kt
- app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt
- app/src/main/java/online/partyrun/partyrunapplication/di/RefreshTokenExpirationNotifier.kt
- app/src/main/java/online/partyrun/partyrunapplication/ui/PartyRunAuth.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/GoogleAuthRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/GoogleAuthRepositoryImpl.kt
- core/datastore/src/main/java/online/partyrun/partyrunapplication/core/datastore/datasource/AgreementDataSource.kt
- core/datastore/src/main/java/online/partyrun/partyrunapplication/core/datastore/datasource/AgreementDataSourceImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/agreement/AgreementUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/auth/GetGoogleAuthUserUseCase.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/auth/AuthNavGraph.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/GoogleAuthClient.kt
- core/testing/src/main/java/online/partyrun/partyrunapplication/core/testing/repository/TestGoogleAuthRepository.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/agreement/AgreementScreen.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/agreement/AgreementViewModel.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashScreen.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashViewModel.kt
기존에는 로그아웃 시, 스플래시와 약관동의를 생략하고 로그인부터 수행하도록 프로세스가 수행되었다.
그러나, 파티런은 로그인 하기 전에 약관동의를 먼저 받기 때문에 이에 맞춰 프로세스 과정이 수정되어야 한다.
최초 로그인 완료 후 로그아웃 시, 스플래시와 약관동의를 생략하지 않고 스플래시 과정부터 다시 시작해 약관동의를 받을 수 있도록 수정한다.
로그인 스크린은 디자인 작업 전. 임시 lottie파일로 대체
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/f6453fce-2162-43bf-b595-d7da09f90b91
> #PAR-221 : 로그아웃 시 스플래시->약관동의 과정부터 시작하도록 변경

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepositoryImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/match/CreateMatchEventSourceListenerUseCase.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MatchDataSource.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MatchDataSourceImpl.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
SSE 프로세스 진행 중 서버와의 연결 또는 통신 중에 오류가 발생할 때 onFailure 메서드가 호출된다.
타임아웃이 발생했거나, 동일 유저가 또 다시 접속을 시도한다거나 할 경우, onFailure가 발생하고 이에 대응하기 위해 onFailure 호출 시 수행할 메소드를 파라미터를 통해 전달
onFailure 발생 시, SSE 상태를 끝냄으로써 예외를 발생시켜 프로세스를 끝낸다.
> fix : SSE Failure 이벤트 발생 시 수행할 메소드 정의

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/ready/BattleReadyScreen.kt
BattleReadyScreen에서 각 ui component들의 위치를 상단으로 조금씩 이동 시킨다.
> refactor : BattleReadyScreen padding값 변경

- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
매칭이 완료되고 다음 Running 스크린으로 넘어가기 전에 아직 연결되어있을지 모르는 SSE 연결과, 다이얼로그 오픈 상태,
즉, 매칭 프로세스에 필요한 진행 상태, 저장 값 등에 대한 전체적인 부분들을 초기화하는 과정을 수행한다.
> fix : 매칭이 완료된 후 러닝 스크린으로 넘어가기 전 매칭 과정 초기화 수행

- app/src/main/AndroidManifest.xml
달리기 앱의 특성상 앱의 화면이 고정되어 있어야 하고, 세로모드로 전체적인 정보를 전달해야 하기에,
가로 방향으로 스크린 방향이 바뀌는 것을 방지한다.
따라서, 파티런 애플리케이션은 세로모드만으로 동작하도록 고정한다.
```
<activity android:screenOrientation="portrait"> // 세로 모드
<activity android:screenOrientation="landscape"> // 가로 모드
```
가로모드를 방지하고 앱 내에서는 세로 모드로만 고정할 것이기에
```<activity android:screenOrientation="portrait">``` 를 manifest에 추가 
또한,
```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools"
tools:ignore="LockedOrientationActivity">
```
manifest에 tools:ignore="LockedOrientationActivity"를 추가하여 화면 방향과 관련된 린트 경고를 제거
> #PAR-245 : 스크린 화면 세로모드 고정

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepositoryImpl.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/match/WaitingEvent.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running/BattleEvent.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running/GpsData.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/RealtimeBattleClient.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/BattleEventResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/WaitingEventResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/MatchDecisionApiService.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchUiState.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
서버 측에서 새로 수정한 API 명세대로 기존에 작성한 코드를 수정하고
collect()를 통해 flow가 emit한 값을 소비할 수 있도록 해 배틀스트림을 처리할 수 있게 변경한다.
1. 매치 서비스 부분 API 명세대로 data class 필드 수정
2. 대결 부분 API 명세대로 data class 필드 수정
3. collect() 추가
4. 불필요한 부분 리팩토링
> #PAR-224 : 바뀐 API 명세에 따른 수정사항 반영 및 flow가 emit한 값을 소비

- app/src/main/java/online/partyrun/partyrunapplication/di/RefreshTokenExpirationNotifier.kt
- app/src/main/java/online/partyrun/partyrunapplication/di/TokenExpirationModule.kt
- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/network/TokenExpirationNotifier.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/AuthAuthenticator.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/di/NetworkModule.kt
1. 기존에는 로그아웃 시 스플래시, 약관동의를 생략하고 로그인 창으로 가도록 하기 위한 intent bundle를 제공했지만,
현재는 로그아웃 시 스플래시, 약관동의 둘 다 보여줄 것이므로 RefreshTokenExpirationNotifier에서 intent bundle 제거
2. TokenNotifier interface 네이밍 변경
> refactor : TokenExpirationNotifier 네이밍 수정 및 intent bundle 제거 

- core/datastore/build.gradle.kts
- core/datastore/consumer-proguard-rules.pro
- core/datastore/src/main/java/online/partyrun/partyrunapplication/core/datastore/UserPreferencesSerializer.kt
- core/datastore/src/main/java/online/partyrun/partyrunapplication/core/datastore/datasource/UserPreferencesDataSource.kt
- core/datastore/src/main/java/online/partyrun/partyrunapplication/core/datastore/di/DataStoreModule.kt
- core/datastore/src/main/proto/user_preferences.proto
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/user/User.kt
- gradle/libs.versions.toml
DataStore Protobuf를 셋팅하여 유저 데이터를 저장한다.
Protocol Buffers는 구글에서 개발한 이진 직렬화 포맷.
Protobuf 플랫폼 및 언어에 독립적이며, 다양한 언어와 시스템에서 데이터를 효율적으로 전송하기 위해 사용됨.
주요 장점은 작은 메시지 크기, 빠른 직렬화/역직렬화 속도 및 강력한 타입 안정성을 제공
https://velog.io/@nohjunh/유저-정보-저장을-위한-Proto-DataStore-Setting
> #PAR-261 : Proto DataStore 설정

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/di/DataModule.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MemberRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MemberRepositoryImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/member/GetUserDataUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/member/SaveUserDataUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/member/SetUserNameUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/member/SetUserProfileUseCase.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MemberDataSource.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MemberDataSourceImpl.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/di/ApiServiceModule.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/di/DataSourceModule.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/UserResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/MemberApiService.kt
- core/testing/src/main/java/online/partyrun/partyrunapplication/core/testing/repository/TestMemberRepository.kt
- feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInGoogleState.kt
- feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInScreen.kt
- feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInViewModel.kt
- feature/sign_in/src/test/java/online/partyrun/partyrunapplication/feature/sign_in/SignInViewModelTest.kt
최초 로그인 시, 서버로부터 토큰 정보를 받고
해당 토큰을 다시 서버로 보내 멤버 서비스로부터 내 UserId, 이름, 이미지를 얻어와 DataSotre Protobuf에 저장하는 과정을 수행한다.
유저 데이터를 저장하고나서야 로그인 과정이 끝나면서 메인 스크린으로 이동.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/9214ffd0-3eeb-4a22-ba68-378082b716e4
> #PAR-263 : 최초 로그인 시 유저 데이터를 가져와 protobuf에 저장한 뒤 메인 스크린으로 이동

- core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/RenderAsyncImage.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/my_page/GetMyPageDataUseCase.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageUiState.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt
마이페이지 스크린에서 유저 닉네임과 유저 프로필 이미지를 볼 수 있어야 한다.
마이페이지를 바텀네비게이션바에서 클릭했을 때 정상적으로 Datastore protobuf에서 유저정보를 불러와 렌더링이 되어 정보 확인이 가능해야 한다.
> #PAR-264 : 마이페이지에서 내 유저 정보를 확인한다.

- app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/BattleRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/BattleRepositoryImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/running/TerminateOngoingBattleUseCase.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/battle/TerminateBattle.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/BattleDataSource.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/BattleDataSourceImpl.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/TerminateBattleResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/BattleApiService.kt
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainViewModel.kt
클라이언트 측에서 배틀이 진행 중인 상황에서 앱을 강제종료 시키면 서버 측에서는 웹소켓 연결이 끊긴 상황을 파악할 수 없다.
따라서, 앱이 다시 구동될 때 최초 1회 기존에 존재하는 배틀 상태가 있다면 종료 시키라는 요청을 보냄으로써 서버 측에서 해당 유저의 배틀 상태를 초기화하는 과정을 수행할 수 있게 한다.
* 현재는 종료만을 제공하지만, 추후 재연결 프로세스 추가 예정
> #PAR-272 : 앱이 처음 구동될 때 기존에 존재하던 배틀 웹소켓 연결을 끊는 요청 전송

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/BattleRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/BattleRepositoryImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/running/DisposeSocketResourcesUseCase.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/RealtimeBattleClient.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/running/BattleRunningScreen.kt
배틀 종료 시, 정책 상 서버측에서는 웹소켓 연결을 일방적으로 끊을 수 없다.
이에 따라 배틀 종료 시, 종료가 된 러너가 직접 토픽 구독과 연결을 끊는 로직을 구현한다.
> #PAR-276 : 배틀 종료 시 웹소켓 토픽 구독과 연결을 끊는다.

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MatchRepositoryImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/match/CancelMatchWaitingUseCase.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/match/CancelMatch.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MatchDataSource.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MatchDataSourceImpl.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/CancelMatchResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/MatchApiService.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
서버 측에서 클라이언트와의 SSE 연결이 끊겼음을 판단해 새로운 매칭이 들어올 수 있게 싱크를 맞추는 과정을 수행할 때, 
단순히 클라이언트의 일방적인 SSE Cancel로는 이를 처리하지 못함.
이에 따라 SSE 연결을 정상적으로 끊기 위한 REST 요청 로직 추가
> #PAR-277 : 매칭 취소 시 취소에 대한 요청을 보낸다.

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/running/BattleRunningScreen.kt
배틀 트랙 위에서 러너들의 마커가 같은 위치에 있을 경우, 겹치게 되어 본인의 마커가 가려질 수 있다.
따라서, 본인의 마커가 최상단에 위치하도록 인터페이스에서 보여줄 수 있게 변경한다.
zIndex 속성을 통해 특정 컴포넌트의 Z축 위치를 조정하여 본인의 마커가 최상단에 위치하도록 변경
* 왼쪽 애뮬레이터는 '석석'으로 로그인 했기에 '석석'이 최상단에 위치
* 오른쪽 애뮬레이터는 '우성진'으로 로그인 했기에 '우성진'이 최상단에 위치
> #PAR-279 : 배틀 트랙 위에 러너들이 겹칠 때 본인의 마커가 최상단에 위치하도록 변경

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/running/BattleRunningScreen.kt
- feature/running/src/main/res/values/strings.xml
서버로부터 받은 데이터를 UI 각 항목에 전처리 후 매핑하는 작업 수행
> #PAR-280 : 배틀 화면에 대한 데이터를 서버로부터 가져와 UI 바인딩

- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashViewModel.kt
로그아웃 시, 스플래시부터 약관동의 까지 다시 수행하므로 불필요한 약관동의 내역을 저장할 필요 없어짐에 따른 불필요한 로직 수정
> refactor : Agreement 내역 저장하는 로직 수정

- app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/res/anim/slide_in_left.xml
- feature/running/src/main/res/anim/slide_in_right.xml
- feature/running/src/main/res/anim/slide_out_left.xml
- feature/running/src/main/res/anim/slide_out_right.xml
- feature/running/src/main/res/values/strings.xml
달리는 상황에서는 뒤로 가기를 할 경우, 아예 대결 상황을 종료시켜야 한다.
따라서, RunningBackNavigationHandler를 적용해 종료 여부를 묻고 그에 따른 처리를 진행한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/4402cf31-2af6-46d5-a552-2796f5aa82ad
> #PAR-288 :  Running 스크린에서 onBackPressedCallback 종료 분기 처리

- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt
매칭 취소 시 SSE 커넥션 부분에서 onFailure로 식별되어 나오는 에러가 있기에
이 부분에서 에러가 떴을 시 클라이언트에게 알려주는 UI 스낵바를 우선적으로 추가한다.
> #PAR-290 : 매칭 취소 관련 Snackbar Message

- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt
매칭 과정에서 대기열 등록 REST 이후 러너들이 3인 모일 때까지 대기하는 SSE 커넥션에서 CompletableDeferred를 통해 SSE 연결~종료까지의 순차성을 보장하고 있다.
그러나 이때, 만약 사용자가 매칭 잡기를 누르고 취소를 한다면 CompletableDeferred가 새로운 CompletableDeferred 인스턴스로 초기화가 되지 않는 문제 발생
waitingEventSSEstate가 closeMatchDialog 호출 이후에 초기화되어야 하지만, connectWaitingEventSource 함수를 호출할 때 여전히 Complete 상태로 유지되는 것이 이유라고 판단했고, 새로운 connectWaitingEventSource 호출마다 새로운 waitingEventSSEstate 인스턴스를 보장하기 위한 작업을 진행한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/f6c26488-35d4-4054-8478-240b0dedafbb
---
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/b8ef61ec-36f6-46d9-8410-3cfa55ec32bf
> #PAR-294 : 매칭 취소 시 SSE 재수행 과정에서의 CompletableDeferred 문제

- feature/sign_in/src/main/java/online/partyrun/partyrunapplication/feature/sign_in/SignInViewModel.kt
- feature/sign_in/src/test/java/online/partyrun/partyrunapplication/feature/sign_in/SignInViewModelTest.kt
사용자가 구글을 통해 회원가입을 시도 시 백엔드 서버로부터 회원가입이 정상적으로 이루어지지 않았다는 응답을 받게 되면,
기존 파이어베이스 서버와의 로그인 연결 시도 또한 취소되어야 하므로 만약, 정상적으로 로그인 요청이 진행되었다면 로그아웃을 하도록 수정
> fix : 백엔드 서버와의 회원가입 시도 실패 시 파이어베이스 로그아웃 보장

- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
매칭 취소 시 스낵 메세지 처리 로직을 Dialog에 속하게 하여 처리했을 때 다이얼로그 로직과 스낵 메세지 로직이 겹쳐 레이아웃이 원하는대로 구성되지 않는 문제 발생
따라서, matchSnackbarMessage를 BattleMainScreen에서 처리하도록 처리
-> 정상적으로 매칭 취소 로직 시나리오 시 스낵메세지 표시
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/d1ddc701-4c57-4276-ab5b-d6cb02cfbc24
> #PAR-296 : matchSnackbarMessage를 BattleMainScreen에서 처리

- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashScreen.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashUiState.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/splash/SplashViewModel.kt
스플래시 과정에서 다음과 같은 과정을 거쳐 구글 로그인이 되어있는지를 확인한다.
GoogleAuthClient에서 getGoogleAuthUser()를 통해 Firebase.auth에서 현재 구글에 로그인된 사용자 정보를 확인하고 UserData 객체로 반환하거나 혹은 사용자가 인증되어 있지 않다면 즉, 로그인이 되어있지 않다면 null을 반환한다.
로그아웃 시 스플래시부터 진행하고 이 때, 사용자 인증을 통해 인증이 없다면 로그인 과정부터 진행해야 하지만 Firebase.auth로부터 정보를 확인하는 과정에서 일부 로그아웃 처리가 되기 전 상태를 받아와 메인 액티비티로 진행되는 이슈 발견
이를 보장하기 위해 기존 약관동의 상태를 활용해 약관동의 상태와 Firebase.auth의 인증 정보가 모두 존재할 시 메인 액티비티로 넘어가도록 수정
> #PAR-297 : 로그아웃 후 스플래시에서 Firebase Auth 사용자 정보 조회 과정에서의 이슈

- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchUiState.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchViewModel.kt
사용자가 매칭 잡기를 중복으로 눌렀을 경우, 상대방이 수락을 누르더라도 정상적으로 매칭 완료가 되지 않는 이슈 발생
매칭버튼의 enabled 상태를 추적해 버튼의 클릭 가능 여부를 판단하려 했지만, enabled가 false일 때 버턴이 사라지는 현상이 있어,
enabled 속성으로 제어하지 않고 onClick에서 조건부로 판단할 수 있게 수정.
> #PAR-298 : 매칭 잡기를 중복으로 클릭할 수 없도록 변경

- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/6ea5e025-a5e9-4a1b-aa63-c28b4fd9d166
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/696b53f1-3370-4650-852d-5d4af873b49e
> fix : PlayerView를 빌드하는 과정에서 생기는 검은 로딩 화면 제거

- core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/RenderAsyncImage.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
.aspectRatio(1f, matchHeightConstraintsFirst = true)
-> UI 요소의 가로세로비(aspect ratio)를 1:1로 설정
-> matchHeightConstraintsFirst가 true로 설정 -> 제약 조건 내에서 먼저 높이를 맞춘 후 그에 맞게 너비 설정
> feat : MyPage Profile Image aspectRatio, matchHeightConstraintsFirst 적용

- .github/workflows/android.yml
- app/src/main/AndroidManifest.xml
- app/src/main/java/online/partyrun/partyrunapplication/ui/PartyRunMain.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleRunnerRecord.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/BattleRunnerStatus.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleRunnerRecordResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleRunnerStatusResponse.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultViewModel.kt
서버로부터 대결 결과를 받아올 때 러너들의 좌표정보(records)도 받아오도록 수정.
좌표 정보로부터 구글맵에 경로를 보여준다.
또한, 특정 러너를 클릭했을 시 그 러너의 정보를 보여줄 수 있도록 한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/4399b929-db47-4107-98c8-50936705178c
> #PAR-305 : 대결을 뛴 러너들의 GPS 좌표를 통해 구글맵에 경로 표시 

- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
매칭 버튼이 2번 클릭이 되지 않도록 한번 클릭이 되면 버튼의 enabled 상태로 바꾸게 해놨지만,
트랙패드와 같이 민감하게 터치가 가능한 경우, 0.002초 사이에 2번 클릭이 되어 매칭 대기열에 Connect Event가 2번 일어나는 문제가 발생
이에, debounce기법을 적용하여 연속 클릭을 제한하는 시간을 설정 → 이 시간 동안의 추가 클릭은 무시하도록 변경
BattleMainScreen의 PartyRunMatchButton을 클릭 했을 시, 두 번 클릭하면
SSE Event가
Connection -> Matched(다른 러너가 매칭을 잡았을 때) -> Connection(2번 클릭으로 인한 잔여 대기열 등록)
다음과 같이 오기 때문에 2번째 Connection에서 onFailure(null)가 발생
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/49e460d3-1939-4567-859f-752764f9d1a8
> #PAR-306 : MatchingButton Debounce 적용

- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/api_call_adapter/ApiResponseCallAdapterFactory.kt
ParameterizedType -> 제네릭을 가진 타입
ex, List<String>이나 Map<Key, Value>처럼 제네릭 타입을 가진 경우
ApiService interface 메서드의 리턴 타입을 보고 적절한 CallAdapter 리턴하는 ApiResponseCallAdapterFactory에서는
제네릭 타입을 요구한다.
callType은 ApiResponse의 제네릭 타입을 확인한다. 즉 리턴 타입이 ApiResponse<T>의 형태인지 확인하는 것인데,
예를 들어, ApiResponse<List<String>>의 경우 List<String>도 ParameterizedType이기에 이것 또한 제네릭 타입인지 확인해야 한다.
이러한 타입 확인은 안전한 형변환과 올바른 타입의 객체 생성을 위해서 필요하고, 기존 이 검사가 없었을 때는, 난독화가 적용된 Release 모드에서는 잘못된 타입에 대한 연산을 시도하게 되어 ClassCastException과 같은 런타임 오류가 발생하게 된다.
따라서, 이러한 타입 검사를 통해 올바른 제네릭 타입을 처리하고,  잘못된 타입에 대한 연산을 방지한다.
package online.partyrun.partyrunapplication.core.network.api_call_adapter
ApiResponseCallAdapterFactory 클래스
> fix : ApiResponseCallAdapterFactory ParameterizedType 체크

- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/MatchDialogScreen.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchDecisionDialog.kt
기존 매칭 수락/거절 여부를 결정하는 MatchDecisionDialog에서 onDismissRequest부분에 setShowDialog를 설정
이로 인해 Dialog 바깥 부분을 클릭 했을 시 자동으로 setShowDialog 메소드가 호출되어 Dialog가 닫힌다.
이 부분은 수락/거절 만으로 로직 처리가 되어야 하기에, 이러한 부분을 수정해주어야 한다.
따라서, 각 과정의 onDismissRequest와 setShowDialog를 제거한다.
package online.partyrun.partyrunapplication.feature.match -> MatchWaitingDialog 부분 
package online.partyrun.partyrunapplication.feature.match.ui -> MatchWaitingDialog 부분 
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/f5929b80-3e29-4bd4-aa5e-3581c601807d
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/90d39bc1-87a3-46b4-8cb2-0dcd692418b5
> #PAR-307 : 매칭 수락/거절 여부를 판단하는 Dialog에서 다른 곳을 클릭했을 때 닫히지 않도록 수정

- app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/battle/BattleNavigation.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/battle_running/BattleRunningNavigation.kt
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleMainScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
사용자가 대결 모드 Screen에서 선택한 목표 거리(=targetDistance)를 Running Feature로 전달하여,
Running Feature에서 이 targetDistance를 기준으로 목표 거리 UI Box를 보여주고 비율 기반 거리 매핑 함수인 distanceToCoordinatesMapper에도 적용해 이 targetDistance에 맞게 매핑이 이루어질 수 있도록 한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/d8ae2546-c106-4739-a4f4-59e4b2eba3ea
> #PAR-311 : 사용자가 선택한 distance를 Running Feature까지 전달해 State에 반영

- core/ui/src/main/java/online/partyrun/partyrunapplication/core/ui/Timer.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/running/BattleRunningScreen.kt
Running이 시작되기 전 카운트다운을 통해 달리기 전 준비상태를 알린다.
그러나, 현재 이 카운트다운에서부터 뒤에 위치한 진행시간이 측정되기 때문에 진행시간이 6초부터 실제 달리기 측정이 시작되고 있다.
따라서, 카운트다운이 끝나고 난 뒤, 진행시간 측정이 시작되도록 FormatRunningElapsedTimer 추가하고 적용한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/1329a87f-5dcf-41d6-8319-b901b204d761
---
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/2d9d2eca-260d-4b37-bd4f-cd2b6482ead6
> #PAR-313 : Running이 시작되기 전 카운트다운 끝나고부터 진행시간 측정

- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt
사용자가 선택한 사용자가 선택한 distance에 따라 결과스크린의 구글맵에서 경로를 보여줘야 한다.
이때, 사용자가 달린 모든 경로를 한 눈에 보여주기 위해 Zoom 배율을 적절히 선택하는게 중요하다.
따라서, 1, 3, 5, 10 Km에 따라 적절히 대응한 float값으로 줌 값이 셋팅될 수 있도록 한다.
---
---
---
> #PAR-312 : 사용자가 선택한 distance에 따라 Result Screen의 GoogleMap Zoom 셋팅

- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/Constants.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/RunningService.kt
- feature/running/src/main/res/values/strings.xml
기존에는 위치 정보 획득 및 전송 프로세스 로직을 ViewModel에서 처리한다. 그러나, ViewModel은 화면 LifeCycle에 종속적이기에 
백그라운드 모드에서도 지속적으로 위치 정보를 얻기 위해 Service가 위치 정보 획득 및 전송 과정을 총괄하도록 변경한다.
위치 정보는 fusedLocationProviderClient를 통해 얻어오기에 Service에서 @Inject를 통해 Client를 주입받아 받아 위치 정보를 획득한다.
따라서, Running Service에서 위치 정보를 획득 후 UseCase를 통해 값을 전달한다.
> #PAR-323 : 위치 정보를 획득 및 전달 로직을 서비스에서 담당하도록 수정

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/di/LocationModule.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/RunningService.kt
SensorManager와 FusedLocationProviderClient를 동시에 사용하여 GPS 오차를 보정한다.
GPS만을 사용하는 경우 실내나 빌딩 사이와 같은 일부 지역에서 GPS 좌표가 확 튀는 등 정확도가 떨어진다. 반면에 센서(가속도계, 자이로스코프 등)는 이러한 환경에서 디바이스 기반의 값을 제공하기 때문에 이 둘의 데이터를 적절히 활용해 신뢰도를 높인다.
SensorManager를 사용해 안드로이드 디바이스의 물리적인 센서(가속도계, 자이로스코프, 자기장 센서 등)에 접근하여 실시간 데이터를 얻는다. 흔들림, 회전, 기울기 등의 사용자 인터랙션을 감지가 가능하지만, 현 티켓 PR에서는 가속도계를 통해 정지해있는지, 움직이고 있는지를 파악한다.
임계값을 정해 센서가 감지하는 움직임이 일정 임계값 이하라면, 그러한 움직임을 무시하고 유효한 GPS 데이터만을 사용할 수 있도록 한다. 이를 통해 정지 상태를 더 정확하게 판별할 수 있도록 하여 신뢰도를 높인다.
> #PAR-321 : SensorManager를 통해 디바이스의 정지 상태를 파악하고 유효하지 않은 GPS 데이터를 필터링한다.

- core/ui/src/main/java/online/partyrun/partyrunapplication/core/ui/SurfaceRoundedRect.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/agreement/AgreementScreen.kt
- feature/splash/src/main/java/online/partyrun/partyrunapplication/feature/splash/agreement/AgreementViewModel.kt
현재 약관동의 시 2가지 선택 항목이 모두 [필수]여서 전체 동의를 통해 다음 단계로 넘어가도록 구성되어있다.
그러나, 약관동의는 개별적으로 선택하는 버튼이 필요하기에 각 항목에 대한 개별 선택 기능을 추가한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/629725fc-ee47-4aed-bf10-7645a8ea6c72
> #PAR-324 : 약관동의 시 개별적인 항목에 대한 선택 추가

- app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/battle/BattleNavigation.kt
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleScreen.kt
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleUiState.kt
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/running/BattleRunningScreen.kt
코드베이스의 가독성과 유지보수를 위해 Battle 관련 파일 명칭을 통일한다.
BattleMain__ 으로 칭했던 Battle의 기본 스크린을 Battle___로 단순표현한다.
BattleContent___ 으로 칭했던 Running Feature Module내 명칭을 BattleContent____로 유지하되, 
내부 변수, 함수, 모델명에도 Content를 붙여 통일성을 부여한다.
> refactor : Battle 관련 파일들 rename 작업 수행 

- app/src/main/AndroidManifest.xml
- feature/battle/build.gradle.kts
- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleScreen.kt
- feature/battle/src/main/res/values/strings.xml
- feature/running/build.gradle.kts
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/finish/FinishScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/permission/CheckMultiplePermissions.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/permission/PermissionDialog.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/ready/BattleReadyScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/BattleRunningScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/BattleRunningService.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/util/DistanceToCoordinatesMapper.kt
- feature/running/src/main/res/values/strings.xml
기존에는 대결 모드만 구현했기에 러닝에 필요한 기능들이 Battle에만 몰려있던 구조였다.
싱글 모드 구현을 시작하기 전에 이러한 한 곳에 몰려있던 파일들을 목적에 맞게 디렉토리화하여 분리하고
Permission 같은 경우, 싱글에서도 확인해야 하므로, battle과 single 모두 접근 가능한 feature/running Module로 로직을 이전한다.
> refactor : 싱글 모드 기능 개발 전 기존 구현부에 대한 재사용성을 위한 리팩토링 수행

- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultScreen.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/RunningResultViewModel.kt
- feature/running_result/src/main/res/values/strings.xml
러닝이 끝나고 난 뒤, 바로 러닝 결과를 조회하는데, 이때 서버로부터 결과를 불러오지 못한다면
RunningResultUiState.LoadFailed로 상태를 변경하고, 
다시 조회하는 버튼을 통해 결과를 못보고 메인으로 돌아가는 상황이 없도록 기능을 추가한다.
> feat : 러닝 결과 불러오기 실패 시 RunningResultUiState.LoadFailed 처리

- app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
- core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/icon/PartyRunIcons.kt
- core/designsystem/src/main/res/drawable/ic_round_remove_24.xml
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/single/SingleNavigation.kt
- feature/single/build.gradle.kts
- feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleScreen.kt
- feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleUiState.kt
- feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleViewModel.kt
- feature/single/src/main/res/values/strings.xml
싱글 모드 구현을 위한 메인 스크린과 기능들을 구성한다.
* ( 현재 싱글 모드에 대한 디자인이 나오지 않았기에, 기본 DesignSystem 설정대로 UI를 구성한다.
추후 디자인이 나오면 수정 예정 )
1. 목표 거리 설정
2. 목표 시간 설정
3. 러닝을 위한 퍼미션 확인 및 획득
혼자서 달리기를 진행하기 전에, 대결 모드와 마찬가지로 달릴 거리를 설정해야 하고
시작하기 버튼을 누르면 퍼미션 확인 후 싱글 모드가 시작된다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/6d57a023-ed5b-4704-8982-7c0355e71515
> #PAR-334 : 싱글모드를 시작하기 위한 메인 스크린과 퍼미션 확인

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/BattleRunningService.kt
1. fusedLocationProviderClient의 lastLocation을 받아올 때 첫 좌표가 가장 마지막에 인식한 위치로 찍히는 문제
->  러너가 이동 후 다시 시작하는 경우에 이전 좌표를 첫 좌표로 받기에 이동 거리가 확 튀게 됨.
-> 플래그를 통해 첫 좌표 제외
2. fusedLocationProviderClient의 Callback LocationResult의 딜레이가 처음 2~3초 가량 발생
-> 이를 감안하기 위해 카운트다운 중 BattleRunningService가 선제적으로 수행될 수 있도록 수정
> fix : Battle Running Service 수행방식 변경

- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/main/BottomNavBarItems.kt
싱글 모드 기능이 일부 가능해짐에 따라 BottomNavBarItems에서 Single 파트에 대한 isLaunched 필드값 변경
> feat : 싱글 모드에 대한 BottomNavBarItems isLaunched -> true로 변경

- app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/SingleRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/SingleRepositoryImpl.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/running_result/GetStoredSingleResultUseCase.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/battle/BattleRunnerRecord.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/battle/BattleRunnerStatus.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/common/RunnerRecord.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/common/RunnerStatus.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/single/SingleResult.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/single/SingleRunnerRecord.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/single/SingleRunnerStatus.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running_result/ui/SingleResultUiModel.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/util/RunningRecordCalculation.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/main/MainNavRoutes.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/running/RunningNavigation.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/running_result/RunningResultNavigation.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/BattleRunnerStatusResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/SingleResultResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/SingleRunnerRecordResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/SingleRunnerStatusResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/util/FormatLocalDateTime.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/single/SingleResultScreen.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/single/SingleResultUiState.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/single/SingleResultViewModel.kt
- feature/running_result/src/main/res/values/strings.xml
- feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleScreen.kt
싱글 모드에서는 사용자가 직접 목표 거리를 설정한다.
싱글 모드를 시작하고 Running Screen에 돌입한 이유부터의 종료 조건은 목표 거리에 도달하거나, 중간에 종료시키거나 2가지이다.
중간에 종료시킬 경우, 현 단계에서는 기록을 저장하지 않는다.
목표 거리에 도달할 경우, 결과를 보여줘야 하기에 SingleResultScreen으로 전환되고, 대결 모드와 마찬가지로 관련 기록 분석 데이터를 보여준다.
다만, 현재 API 명세가 없어 서버와 연동이 안된 상태이므로 SingleResultScreen에서 보여주는 데이터는 임시 더미 데이터를 통한 UI 환경으로 제공한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/cec3c381-8acc-4657-8513-35a3b4454d2e
> #PAR-341 : 싱글 모드에서 목표 거리 도달 시 결과를 보여주는 프로세스 구현 

- app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
'돌아가기' 버튼을 눌렀을 때, navigateToTopLevel() 메소드가 수행되는데, 
기존에는 이 메소드에 navController popUpTo가 적용 되어있지 않아 BackStack에 ResultScreen이 그대로 있었음.
popUpTo를 적용해 제외해주는 과정을 거치도록 변경
> feat : RunningResult에서 '돌아가기' 버튼을 눌렀을 때 popUpTo 적용

- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/Constants.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/SingleRunningScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/SingleRunningService.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
싱글모드 시에 일시정지, 재시작, 종료 로직을 구현한다.
초기 버튼 패널에는 일시정지만 있고, 일시정지를 클릭했을 때 재시작과 종료 버튼 패널로 전환되는 방식이다.
* 사용자 편의성을 위해 다음과 같은 기능을 추가 구현
자동으로 사용자 디바이스 움직임을 감지하여 작동을 일시정지하거나 재시작하는 서비스와, 사용자의 의도에 따라 종료하는 로직
1. 사용자가 뛰다가 잠시 쉬거나 멈추게 되면, 앱이 자동으로 그것을 감지하여 일시정지 상태로 전환 -> 사용자가 직접 앱을 건드리지 않아도 되므로 달리기에만 집중 가능
2. 일시정지 상태에서 사용자의 움직임이 감지되면 자동으로 재시작 
3. 만약 사용자가 멈추었는데 앱이 계속 거리를 측정한다면, 의미없는 데이터이므로. 자동 일시정지 기능을 통해 데이터의 정확성 향상
안드로이드 Sensor로부터 받는 속도 데이터를 기반으로 특정 임계값(THRESHOLD) 이하일 때를 감지 ->
이 임계값 이하의 속도가 연속으로 감지될 경우 (여기서는 3회 이상-정책에 따라 수정 예정), 서비스는 자동으로 일시정지 상태로 전환
사용자의 움직임이 재개되면, 서비스는 자동으로 재시작
이러한 자동 상태 변경 로직은 브로드캐스트와 리시버를 통해 통신
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/bc0ed834-6933-4b4e-8d40-f3fc244d11a0
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/0764acbd-d79b-4c9 …
> #PAR-343 : 싱글모드 일시정지, 재시작, 종료 로직 구현 

- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/Constants.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/SingleRunningScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/SingleRunningService.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
사용자가 계속 뛰다가 잠깐 멈춰서 일시정지 된거는 다시 뛰었을 떄 자동으로 재시작되도록 해주는게 맞지만,
사용자가 직접 일시정지를 눌렀을 때는 사용자에게 선택권을 주어야 하기에 자동으로 재시작되도록 해주면 안된다.
따라서, 사용자가 직접 누른 경우와 자동으로 감지하여 일시정지한 경우를 구분할 수 있도록 일부 변경을 수행한다.
->
사용자가 일시정지를 누른 경우는 디바이스의 움직임이 감지되어도 재시작이 되지 않도록 한다.
* 사용자 디바이스의 움직임이 없을 때는 GPS 데이터를 수집하지 않는다. -> 무의미한 데이터라 판단
* 사용자 디바이스의 움직임이 일정 카운트동안 없으면 "자동 일시정지"
* "자동 일시정지" 상태에서 사용자 디바이스의 움직임이 감지되면 "자동 재시작"
* 사용자가 직접 일시정지를 누른 경우 -> "사용자 일시정지"
* "사용자 일시정지" 상태에서는 디바이스 움직임이 감지되어도 "자동 재시작" 되지 않고 사용자가 직접 재시작을 눌러야지만 프로세스 재개
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/252b9645-0a1b-4fe3-afda-7af6a4f83e9f
1. 사용자 움직임 감지
2. 사용자 움직임이 없을 땐 GPS 데이터 수집 중단
3. 일정 카운트동안 움직임이 없으면 "자동 일시정지"로 전환 (마우스 움직임 == 실제 디바이스 기기의 움직임 표현)
4. 사용자 움직임이 포착되면 "자동 재시작"
5. 사용자가 직접 일시정지를 누를 경우 -> 디바이스 움직임이 감지되어도 일시정지 상태 유지
6. 직접 …
> #PAR-347 : 싱글모드 중 사용자가 일시정지를 누른 경우와, 달리는 중 움직임이 없어 일시정지가 된 경우 로직 분리

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
기존 유사 러닝앱은 10미터 이상만 달리면 데이터를 저장하고 있다.
그러나, 10미터와 같은 적은 거리의 데이터를 저장할 필요성을 못느끼기에,
최소 100미터 이상 달린 데이터들만 저장하고 결과 조회를 할 수 있도록 기능을 추가한다.
> #PAR-346 : 싱글모드 종료 시 일정 거리 이상 달리지 않았으면 결과 조회를 하지 않는다.

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
기존 SingleRunningService는 카운트다운이 3초가 될 때 활성화되었다. (최초 1회 GPS 데이터만 무시하기 위해)
그러나, 지금은 2번째 GPS Data를 LastLocation으로 넣는 로직이 추가로 들어가기에 유의미한 거리비교가 수행되기 위해서는 더 빠른 시간에 RunningService가 활성화 되어야 한다.
최초 1회 GPS data는 이전에 찍힌 가장 최신 GPS data가 찍히므로 무시 (멀리 찍힌 데이터가 찍힐 수도 있음)
최초 1회 GPS data가 찍힌 이후 약 3초 후에 현재 위치가 반영이 보장된 유효한 GPS data가 찍힘
2번째 GPS data는 LastLocation을 업데이트하므로 사실상 카운트다운 시작 시에 RunningService를 활성화시키면
카운트다운이 끝나자마자 유의미한 거리비교가 가능
> refactor : startSingleRunningService 수행 카운트다운 변경

- .github/workflows/android.yml
- core/common/src/main/java/online/partyrun/partyrunapplication/core/common/Constants.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MemberRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/MemberRepositoryImpl.kt
- core/datastore/src/main/java/online/partyrun/partyrunapplication/core/datastore/datasource/UserPreferencesDataSource.kt
- core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/icon/PartyRunIcons.kt
- core/designsystem/src/main/res/drawable/ic_add_circle_filed_24.xml
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/member/SaveUserDataUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/member/UpdateProfileImageUseCase.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/member/UpdateUserDataUseCase.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/user/User.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MemberDataSource.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/MemberDataSourceImpl.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/request/UserDataRequest.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/UserResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/MemberApiService.kt
- core/testing/src/main/java/online/partyrun/partyrunapplication/core/testing/repository/TestMemberRepository.kt
- feature/my_page/build.gradle.kts
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageUiState.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileUiState.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
- gradle/libs.versions.toml
사용자 프로필 이미지 수정 기능을 추가한다.
Multipart를 통해 이미지를 업로드한다.
1. Multipart 형식은 여러 종류의 데이터를 함께 전송할 수 있는 유연한 방법 제공
2. 효율적인 파일 업로드: 이미지 파일과 같은 이진 데이터를 효율적으로 전송. Multipart 요청은 파일 데이터를 분할하여 전송하므로 대용량 파일의 업로드 관리 이점
3. 서버 호환성: 대부분의 서버 및 백엔드 API는 Multipart 형식 지원. 이미지 업로드에 대한 서버 호환성 확보
4. 메타 데이터
5. 보안, 서버 처리 용이성
> #PAR-327 : 프로필 사진 수정 기능 추가 / API 연동 

- feature/settings/src/main/java/online/partyrun/partyrunapplication/feature/settings/SettingsViewModel.kt
- feature/settings/src/main/java/online/partyrun/partyrunapplication/feature/settings/UnsubscribeScreen.kt
회원탈퇴를 진행할 때 딜레이 문제가 발생할 경우,
회원탈퇴 Confirm이 됐음에도 약관동의 스크린부터 시작한 로그인 프로세스를 진행하지 않고
앱 메인 스크린에서 다시 시작되는 문제 발생
->
약관동의 Boolean 값 처리를 위한 UseCase를 SettingViewModel에서 함께 처리할 수 있도록 수정
>  #PAR-355 : 회원탈퇴 시 약관동의부터 다시 받도록 보장

- app/src/main/java/online/partyrun/partyrunapplication/AuthActivity.kt
- app/src/main/java/online/partyrun/partyrunapplication/MainActivity.kt
- app/src/main/res/values/strings.xml
기존 In-App-Update를 AuthActivity에서 수행하도록 했는데, 이 경우 화면 전환이 많은 PartyRun AuthActivity 특성 상 업데이트 창이 오래 지속되지 못한다.
따라서, 인앱 업데이트 프로세스를 MainActivity에서 수행하도록 변경한다.
또한, AppUpdateType을 FLEXIBLE에서 IMMEDIATE로 변경
> refactor : 인앱 업데이트를 MainActivity에서 수행하도록 변경

- feature/battle/src/main/java/online/partyrun/partyrunapplication/feature/battle/BattleScreen.kt
- feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/PartyScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/permission/HandlePermissionActions.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/permission/SettingPermissionVariables.kt
- feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleScreen.kt
방 만들기와 방 참여하기 모두 위치 기반과 알림 퍼미션 허용되어야 가능하도록 적용해야 한다.
이를 위해 버튼 클릭 시 다중 퍼미션 획득 여부를 판단하고 없다면 허용하도록 유도한다.
두 버튼 모두 짧은 순간에 연속 클릭이 되는 것을 방지할 수 있도록 디바인스 기법을 적용한다.
> #PAR-367 : 파티 멀티 퍼미션 및 디바인스 적용 

- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/running/RecordDataWithDistance.kt
- feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/room/PartyRoomViewModel.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/battle/BattleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/component/RunningExitConfirmationDialog.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/BaseRunningService.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/SingleRunningService.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
- feature/running/src/main/res/values/strings.xml
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/single/SingleResultScreen.kt
1. 기존 100m였던 Single MINIMUM_FINISH_DISTANCE를 50으로 변경
2. Single, Battle 종료 달리기에 대한 안내 멘트 별도 처리
3. completedEventProcess에서는 SnackbarMessage를 출력하지 않도록 변경
4. Single은 자체적으로 거리 조정이 가능하므로 'km'로 고정하던 Battle과는 달리 'm' 포맷으로 출력
> refactor : 싱글, 배틀 디테일 수정

- feature/party/src/main/java/online/partyrun/partyrunapplication/feature/party/room/PartyRoomViewModel.kt
방장 혼자 있을 때는 대결를 시작하지 못하도록 제한하는 기능을 추가한다.
파티 러닝은 반드시 2인 이상이 가능하도록 제한
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/aa9e8bec-ebd2-4e1b-b055-3a12e3a634c5
1. 1인일 경우 제한 메세지
2. 타인 참여
3. 2인부터 시작 시 Running 기능 수행
>  #PAR-368 : 방장 혼자 있을 때는 파티 시작을 못하도록 제한

- app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/my_page/MyPageNavigation.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
마이페이지는 바텀 네비게이션을 통해 이동하는 findStartDestination이다.
따라서 기존에 있던 필요없는 뒤로가기 기능을 제거한다.
> refactor : 마이페이지에 불필요한 navigateToBack 기능 제거

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/running/SingleRunningScreen.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentUiState.kt
- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/single/SingleContentViewModel.kt
Text Composable의 너비가 달린시간의 변화에 따라 동적으로 달라질 때 이를 고정하는 작업을 수행하고자 했다.
러닝 시간을 표현할 때 1의 너비가 다른 숫자들의 너비와 다르기에 상위 컴포저블에서 Center로 Alignment를 고정했을 때 텍스트가 조금씩 움직이는 문제가 있었다.
즉, 00:00:00 포맷의 너비와 00:00:01 포맷의 너비가 다르기에 Center 정렬로 디바이스의 중앙에 러닝시간을 표현할 때 시간 변화에 따라 움직이는 문제
**1. 달린시간 width 고정**
달린 시간은 Center 정렬하여 표현되어야 하기에 00:00:00 포맷으로 width를 맞춰나도 00:01:00 혹은 00:00:10 처럼 1이 들어가면 너비가 달라지기에 Center에 정확히 시간이 위치하지 못하게 된다.
**2. '1'의 갯수에 따라 width를 동적으로 반영**
그러나, 이 방법은 근본적인 원인 해결이 아니라 현상태와 동일하므로 패스.
**3. Monospace**
파티런은 Pretendard폰트를 사용하기에 기본 FontFamily의 monospace를 활용할 수 없었다.
이에 직접 각 텍스트의 하나하나마다 width를 고정하려고 했으나, 00:01:00과 같은 포맷이 될 경우 1 양 옆에 space가 생겨 적절하지 못했다.
그렇다고 각 텍스트마다 space를 동일하게 주면 0 0 : 0 0 : 0 0 이런 식의 포맷이 되는데, 이는 적절하지 않았다.
**4. second에만 width 고정** 
변화가 가장 많은 seconds에만 width를 고정해 시간 변화에 따른 텍스트 너비의 변화를 …
> #PAR-376 : 달린 시간의 second의 width를 고정하여 시간 변화에 따른 너비 변화 방지

- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileViewModel.kt
카메라로 찍은 사진 같은 경우 MB가 나오게 된다. 이 경우 아래와 같은 문제가 예상되기에 KB로 압축하는 과정이 들어가야 된다.
1. 전송 시간: 큰 파일 전송 -> 시간 더 많이 소요 -> 사용자가 더 긴 대기 시간을 느낌
2. 서버 저장 비용: 이미지를 서버에 저장하는 경우, 큰 이미지는 더 많은 저장 공간 차지 -> 스토리지 비용 증가
3. 메모리 이슈: 고해상도 이미지를 로드하고 처리할 때 앱의 메모리 사용량 증가
> #PAR-371 : 프로필 이미지 전처리

- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/single/SingleTargetDetails.kt
- feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleScreen.kt
- feature/single/src/main/java/online/partyrun/partyrunapplication/feature/single/SingleViewModel.kt
싱글모드를 위해 목표 거리와 시간을 설정하는 로직을 ViewModel에서 처리하지 않고, SingleTargetDetails 도메인 모델 내 거리와 시간의 증감 및 표시 방식과 관련된 핵심 규칙을 정의해 처리한다.
이를 통해 뷰모델이 좀 더 간결해지며 UI 상태 관리에 집중할 수 있고, 도메인 모델의 책임과 행동이 명확하게 정의되어 도메인 복잡성 감소, 코드의 가독성과 유지 보수성이 향상되는 이점을 챙길 수 있다.
1. 캡슐화:  SingleTargetDetails는 자신의 상태와 관련된 비즈니스 로직을 자체적으로 포함 -> 객체의 상태와 그 상태를 변경하는 행동이 같은 곳에서 관리되므로 캡슐화 강화
2. 유지 보수성: 도메인 로직이 모델 내에 위치하면, 해당 도메인에 관련된 변경이 필요할 때 모델만 확인하면 됨 -> 유지보수, 리팩토링 수월
3. 재사용성: SingleTargetDetails와 같은 도메인 모델은 여러 뷰모델이나 다른 계층에서도 사용될 수 있기에, 로직이 모델 내에 포함되어 있으면, 재사용 시에도 해당 로직을 함께 가져가게 되므로 중복 코드 감소
4. 테스트 용이성: 도메인 모델에 로직이 포함되어 있으면, 해당 로직에 대한 유닛 테스트를 작성하기 수월. 모델의 상태와 행동을 분리해서 테스트할 수 있으므로, 테스트의 범위와 목적이 명확해짐
5. 가독성: SingleViewModel과 같은 뷰모델은 UI와 관련된 작업에 집중. 로직이 도메인 모델로 이동함으로써 뷰모델이 더 간결하고 명확해지며, 각 계층의 책임이 명확히 구분됨
> refactor : Single 설정 로직을 domain model의 확장함수에서 처리하도록 변경

- feature/running/src/main/java/online/partyrun/partyrunapplication/feature/running/service/BaseRunningService.kt
러닝 중 앱을 강제종료할 시 기존에는 foreground Service 작업이 정상적으로 종료되지 않는 문제 파악
이에,
안드로이드 Service의 onTaskRemoved()를 이용해 클린업 작업을 수행하도록 수정한다.
이 메서드는 사용자가 최근 앱 목록에서 앱을 제거하거나 "Force Stop"을 사용하여 앱을 종료할 때 호출된다.
즉, 이 메서드를 활용하면 앱이 강제 종료될 때 필요한 작업을 수행할 수 있다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/bbc3dd5f-6b8e-46e9-96e7-90287a10a4fe
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/c9fd114e-4665-4878-b833-757be58be8ed
> fix : 러닝 중 앱 강제종료 시 Service onTaskRemoved() 클린업 Task 수행

- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt
인터페이스 상 TopAppBar의 back arrow 클릭 시 의도대로 동작하지만, 디바이스 기기 내 back navigation시 프로필 이미지 변경 사항이 바로 반영되지 않는 현상이 있다.
따라서, BackNavigationHandler를 적용해 마찬가지로 navigateToMyPage() 메소드를 호출할 수 있도록 하여 의도대로 동작하도록 한다.
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/e3d35a04-6333-47e0-a262-594c27d93191
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/41424faa-4fb5-4df1-8239-7f27aee3e7cb
> feat : ProfileBackNavigationHandler 적용

- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchResultDialog.kt
- feature/match/src/main/java/online/partyrun/partyrunapplication/feature/match/ui/MatchWaitingDialog.kt
- feature/match/src/main/res/values/strings.xml
MatchWaitingDialog와 MatchResultDialog Colon 띄어쓰기 수정
> refactor : match dialoag Colon 간격 수정

- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/ResultRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/ResultRepositoryImpl.kt
- core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/ShimmerEffect.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/my_page/GetComprehensiveRunRecordUseCase.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/my_page/ComprehensiveRunRecord.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/my_page/TotalRunningTime.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/ResultDataSource.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/ResultDataSourceImpl.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/ComprehensiveRunRecordResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/TotalRunningTimeResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/ResultApiService.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageUiState.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/component/MyPageProfile.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/component/RunningHistory.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/component/StatusElement.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/profile/ProfileScreen.kt
마이페이지 유저 정보 박스 아래에 총 달린 거리, 평균 페이스, 총 누적 거리를 보여줄 수 있는 스테이터스 바에 API 연동 결과를 보여준다.
**특히, 마이페이지 같은 경우 정보를 가져오는 API가 많기에 ShimmerEffect를 적용하여 다음과 같은 이점을 얻는다.**
1. 보다 나은 사용자 경험(UX): 데이터 로딩 시간 동안 사용자에게 빈 화면을 보여주는 것보다 무언가 로딩되고 있다는 것을 시각적으로 표현하는 것이 더 나은 UX 제공
2. 콘텐츠의 예상 형태 표현: 로딩되는 콘텐츠의 기본 형태와 구조를 나타내어 사용자로 하여금 콘텐츠가 로드되는 동안 어떤 형태의 정보가 제공될지 미리 예상할 수 있게 함
3. 응답성 향상: 실제 콘텐츠가 준비되기 전에 UI를 빠르게 표시함으로써 앱의 반응성 향상
4. 로딩 지연의 인식 감소: 사용자의 주의를 분산시키고, 실제로 데이터 로딩에 걸리는 시간 즉, 지루함을 느끼는 것을 줄임.
* ShimmerEffect를 보여주기 위해 의도적으로 delay를 추가한 상태에서 촬영
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/56d1510f-a5b9-4147-8099-2cc18021ff6c
> #PAR-380 : 종합기록 조회 API 연동 + ShimmerEffect 적용

- app/src/main/java/online/partyrun/partyrunapplication/navigation/MainNavHost.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/ResultRepository.kt
- core/data/src/main/java/online/partyrun/partyrunapplication/core/data/repository/ResultRepositoryImpl.kt
- core/designsystem/src/main/java/online/partyrun/partyrunapplication/core/designsystem/component/ShimmerEffect.kt
- core/domain/src/main/java/online/partyrun/partyrunapplication/core/domain/my_page/GetSingleHistoryUseCase.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/my_page/RunningHistoryDetail.kt
- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/my_page/SingleRunningHistory.kt
- core/navigation/src/main/java/online/partyrun/partyrunapplication/core/navigation/my_page/MyPageNavigation.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/ResultDataSource.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/datasource/ResultDataSourceImpl.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/SingleHistoryDetailResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/SingleHistoryResponse.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/service/ResultApiService.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageScreen.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageUiState.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/MyPageViewModel.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/component/RunningHistory.kt
- feature/my_page/src/main/java/online/partyrun/partyrunapplication/feature/my_page/component/StatusElement.kt
마이페이지에서 싱글 모드 단일 조회 API를 연동하고 결과를 보여준다.
원하는 기록을 클릭할 시 러닝 결과를 볼 수 있게 ResultScreen으로 전환
**특히, 마이페이지 같은 경우 정보를 가져오는 API가 많기에 ShimmerEffect를 적용하여 다음과 같은 이점을 얻는다.**
1. 보다 나은 사용자 경험(UX): 데이터 로딩 시간 동안 사용자에게 빈 화면을 보여주는 것보다 무언가 로딩되고 있다는 것을 시각적으로 표현하는 것이 더 나은 UX 제공
2. 콘텐츠의 예상 형태 표현: 로딩되는 콘텐츠의 기본 형태와 구조를 나타내어 사용자로 하여금 콘텐츠가 로드되는 동안 어떤 형태의 정보가 제공될지 미리 예상할 수 있게 함
3. 응답성 향상: 실제 콘텐츠가 준비되기 전에 UI를 빠르게 표시함으로써 앱의 반응성 향상
4. 로딩 지연의 인식 감소: 사용자의 주의를 분산시키고, 실제로 데이터 로딩에 걸리는 시간 즉, 지루함을 느끼는 것을 줄임.
* ShimmerEffect를 보여주기 위해 의도적으로 delay를 추가한 상태에서 촬영
https://github.com/SWM-KAWAI-MANS/party-run-application/assets/75293768/812ba7b3-9889-4163-b701-84a6e54cc262
> #PAR-381 : 싱글 모드 단일 조회 API 연동 + Shimmer Effect 적용

- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/battle/BattleResultScreen.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/component/MapWidget.kt
- feature/running_result/src/main/java/online/partyrun/partyrunapplication/feature/running_result/single/SingleResultScreen.kt
마이페이지에서 기록 조회 시, 사용자로부터 ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION 권한이 허용되지 않았으면
java.lang.SecurityException: my location requires permission ACCESS_FINE_LOCATION or ACCESS_COARSE_LOCATION 발생
->
러닝을 위한 모든 기능에 대해서는 권한 체크를 진행해 이러한 Exception이 발생하지 않지만, 마이페이지 같은 경우 권한이 없더라도 기록 조회 자체는 가능하도록 해야 한다.
따라서, 예외를 발생시키는 Property인 isMyLocationEnabled를 마이페이지에서 접근한 경우 false로 설정함으로써 방지한다.
> #PAR-384 : GoogleMap isMyLocationEnabled property Exception 처리

- core/model/src/main/java/online/partyrun/partyrunapplication/core/model/util/RunningRecordCalculation.kt
- core/network/src/main/java/online/partyrun/partyrunapplication/core/network/model/response/ComprehensiveRunRecordResponse.kt
달리기 앱에서 러닝 기록 평균 페이스는 보통 (분'초'')/킬로미터 단위로 나타낸다.
싱글, 대결모드 결과 조회 시 평균 페이스 계산은 위 공식을 따르지만,
서버로부터 받은 마이페이지 종합기록 중 평균페이스는 m/s로 오기 때문에 분/킬로미터 단위로 변환하는 과정을 거치도록 변환함수를 추가한다.
> feat : m/s로 계산된 평균 페이스를 분/킬로미터 단위로 변환
